export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const ADD_ORDER_SUMMARY = 'ADD_ORDER_SUMMARY';
export const DELETE_ORDER_SUMMARY = 'DELETE_ORDER_SUMMARY';